# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jestor
# Description of the Site
description: Software Developer
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Portfolio, software development, programming
# URL for the Image of custom Favicon
favicon-url: /favicon_io/favicon-32x32.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://c4.wallpaperflare.com/wallpaper/87/197/280/digital-art-low-poly-geometry-minimalism-wallpaper-preview.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jestor@gmail.com
twitter_username: hatdogcoder
linkedin_username: jesús-andrés-torrejón-león-511351190
github_username:  jestorDev
youtube_channel_id: UC0JstG4TDBT9WnUui5pHpuQ

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: jestor

# Name of the Author
author-name: jestor
# URL for the Image of the Author
author-image: https://github.com/jestorDev/hello-world/blob/master/1F.jpg?raw=true
# 60 Words About the Author
author-about: CS major with knowledge of web development, algorithms, programming in JavaScript, Python and C++, mainly interested in the development of image processing and web applications . I've participated as a research assistant in the BigData-HCP lab at CTIC-UNI.

author-photo:  https://pbs.twimg.com/profile_images/1464076803618840579/mlqmZAEd_400x400.jpg

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/jestor

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
